#!/usr/bin/env python3
"""Generate FilmLab's original vintage looks as 33-point .cube LUTs.

    python3 scripts/make_vintage_luts.py FilmLab/LUTs

These looks are designed for FilmLab and dedicated to the public domain (CC0 1.0), so unlike the
adapted RawTherapee and PictureFX looks they carry no conditions. Needs NumPy.

Each recipe is a few steps applied to sRGB values, in this order:
  mix         3x3 channel mix (cross-processing casts)
  gamma       per-channel midtone shift; above 1 darkens that channel's midtones
  contrast    S-curve strength; negative flattens
  saturation  multiplier around luminance
  split       colour added to shadows and to highlights, weighted by luminance
  lift, roll  per-channel output black and white points (faded blacks, soft creamy highlights)
"""
import os
import sys

import numpy as np

SIZE = 33

RECIPES = {
    "1975": dict(
        gamma=(0.93, 1.0, 1.12), contrast=0.15, saturation=0.72,
        split=((-0.04, 0.02, 0.05), (0.06, 0.03, -0.04)),
        lift=(0.08, 0.07, 0.09), roll=(0.94, 0.90, 0.78),
    ),
    "Sunbleached": dict(
        gamma=(0.92, 0.96, 1.06), contrast=-0.1, saturation=0.6,
        split=((0.0, 0.0, 0.0), (0.05, 0.04, 0.0)),
        lift=(0.14, 0.13, 0.12), roll=(0.97, 0.95, 0.85),
    ),
    "Expired": dict(
        mix=((0.95, 0.05, 0.0), (0.02, 0.96, 0.02), (0.0, 0.08, 0.92)),
        gamma=(1.04, 0.95, 1.02), contrast=0.1, saturation=0.82,
        split=((0.03, -0.02, 0.04), (-0.02, 0.03, -0.01)),
        lift=(0.08, 0.05, 0.09), roll=(0.92, 0.96, 0.87),
    ),
    "Disposable": dict(
        gamma=(1.0, 0.96, 1.04), contrast=0.35, saturation=1.08,
        split=((-0.03, 0.02, 0.02), (0.04, 0.02, -0.04)),
        lift=(0.03, 0.045, 0.05), roll=(1.0, 0.98, 0.9),
    ),
    "Memory": dict(
        gamma=(0.88, 0.95, 1.18), contrast=0.12, saturation=0.8,
        split=((0.02, 0.0, -0.02), (0.06, 0.04, -0.03)),
        lift=(0.07, 0.06, 0.04), roll=(0.97, 0.92, 0.78),
    ),
    "Tide": dict(
        gamma=(1.03, 0.98, 0.96), contrast=0.18, saturation=0.78,
        split=((-0.07, 0.03, 0.06), (0.06, 0.02, -0.03)),
        lift=(0.05, 0.08, 0.09), roll=(0.97, 0.93, 0.87),
    ),
}


def apply(rgb, mix=None, gamma=(1, 1, 1), contrast=0.0, saturation=1.0,
          split=((0, 0, 0), (0, 0, 0)), lift=(0, 0, 0), roll=(1, 1, 1)):
    c = rgb.copy()
    if mix is not None:
        c = c @ np.array(mix).T
    c = np.clip(c, 0, 1) ** np.array(gamma)
    if contrast:
        s_curve = c * c * (3 - 2 * c)
        c = c + (s_curve - c) * contrast
    luma = (c @ np.array([0.2126, 0.7152, 0.0722]))[..., None]
    c = luma + (c - luma) * saturation
    luma = np.clip(luma, 0, 1)
    c = c + np.array(split[0]) * (1 - luma) ** 2 + np.array(split[1]) * luma ** 2
    c = np.clip(c, 0, 1)
    return np.array(lift) + (np.array(roll) - np.array(lift)) * c


def grid():
    v = np.linspace(0, 1, SIZE)
    b, g, r = np.meshgrid(v, v, v, indexing="ij")  # red changes fastest when flattened
    return np.stack([r, g, b], axis=-1).reshape(-1, 3)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    for name, recipe in RECIPES.items():
        lut = apply(grid(), **recipe)
        with open(os.path.join(out_dir, f"{name}.cube"), "w") as fh:
            fh.write("# FilmLab original look, generated by scripts/make_vintage_luts.py\n")
            fh.write("# CC0 1.0 - dedicated to the public domain: https://creativecommons.org/publicdomain/zero/1.0/\n")
            fh.write(f'TITLE "{name}"\nLUT_3D_SIZE {SIZE}\n')
            for row in np.clip(lut, 0, 1):
                fh.write("%.6f %.6f %.6f\n" % tuple(row))


if __name__ == "__main__":
    main()
